### ISSUE TITLE
bit porno not work

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl.xxx#10]
bit porno not work yet, i've tested your chenge and link not work
here is the debug log
https://pastebin.com/raw/5GHSsJry

**Comment by Gujal00** [comment]
First install smr.xxx from zip.
Then install smr link tester from smrzips repo and then use that to test any embeds.
I cant vouch for any other addon here for testing. It certainly works when smr.xxx is properly installed as a dependency and imported by the addon
Basically whatever addon needs to import the xxx plugins as shown here
https://github.com/jsergio123/script.module.resolveurl.xxx/blob/master/README.md
