### ISSUE TITLE
Streamtape not resolving

### ISSUE THREAD

**Issue by tetzy** [jsergio123/script.module.resolveurl.xxx#12]
I hope I'm posting this to the correct place: 

For the past week or so, links to files hosted by Streamtape (both to download and play) return the following:

"Streamtape link could not be resolved"

I'm hoping you can assist. Thanks .

**Comment by Gujal00** [comment]
Already fixed in https://github.com/jsergio123/script.module.resolveurl/commit/27fa768f8b100310b69e6191aeb722f9492a2e09
