### ISSUE TITLE
Voyeurhit is broken

### ISSUE THREAD

**Issue by boxkim14** [jsergio123/script.module.resolveurl.xxx#14]
Hi,

I guess voyeurhit is broken. Can you please fix it?

Thank you

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl.xxx/commit/080b1823dc1a69611bef76ae089584668855451d

**Comment by boxkim14** [comment]
Hi @Gujal00 ,

Thanks to fix the issue very quick. 
But I fail to test it. Maybe I did something wrong:
I get the video_url from the web: 

L2dldF9maWxlLzЕvNTYyZDNjOTВjМThhY2МxZjJjYTljZDIwNjI1ZjNmOTU4YTЕ2NWFkZmQ3LzМ0NTАwМС8zNDUxNTМvМzQ1МTUzX2hxLm1wNС8,ZD02МDImYnI9МjМ5JnRpPTЕ2МTЕwNzI4МTI~

And the self._decode fails to decode this value and throw this error:
 Error: chr() arg not in range(256)

Can you please help me to test it?

Thanks in advance for your help

**Comment by Gujal00** [comment]
How are you testing this? Test the embed in smr_link_tester
The above video_url decodes correctly to `/get_file/1/562d3c90c18acc1f2ca9cd20625f3f958a165adfd7/345000/345153/345153_hq.mp4/?d=602&br=239&ti=1611072812`

**Comment by boxkim14** [comment]
Sorry that I don't know how to use smr_link_tester. :(
I just copy the self._decode in the py and test the _decode in my PC eclipse (Python version 2.7)

When a = 0, I print the following values:
n,o,s,r = 15 59 34 42
i = ?��
There is already a strange value in the first iteration. :(
I don't know what I did wrong :(. Do I copy correctly the self._decode function ?

**Comment by boxkim14** [comment]
Here is the link:
'https://voyeurhit.com/videos/342857/naked-women-on-the-beach/'
<https://voyeurhit.com/videos/344769/topless-beach-1/>

I just import the resolverurl and voyeurhit.py in my eclipse python.
I run it and I see there is unicode character in the resp.get('video_url')
then voyeurhit.py raises exception in line:
n = t.index(e[a]) (when a=0)
because e contains unicode character.

**Comment by Gujal00** [comment]
Your issue is Python 2.7. you need to handle encodings correctly otherwise you will get that error. Will work fine without issues in Python 3.7+

**Comment by boxkim14** [comment]
Thanks a lot for answering my question. You are so good to do this reverse
engineering. I really don't know how you can do it.

**Comment by Gujal00** [comment]
@boxkim14 
I have just pushed https://github.com/jsergio123/script.module.resolveurl.xxx/commit/2a631283b4f09e14828fe51c3db4e77804861ffc
This code will work in Python 2.7 and 3.7+

**Comment by boxkim14** [comment]
Thanks a lot. It's working for 2,17.
