### ISSUE TITLE
Streamtape resolvve issue

### ISSUE THREAD

**Issue by tetzy** [jsergio123/script.module.resolveurl.xxx#16]
For the past few days I've been getting the "Streamtape link could not be resolved" error when I try to download and play titles. I've tried links from several sources and all report the same error.

![Screenshot from 2021-09-10 01-11-0o2](https://user-images.githubusercontent.com/59111079/132815500-ef6f23bf-2ad3-4688-81e7-855de58c56b9.jpg)

I'm hoping you can help.
Thanks.

**Comment by Gujal00** [comment]
Screenshots are of no use as it does not even show which version of smr is in use. It definitely works with the latest release
