### ISSUE TITLE
Hi Mate...

### ISSUE THREAD

**Issue by TheGridRepo** [jsergio123/script.module.resolveurl.xxx#5]
was wondering ...i been using erotik xxx addon and some of the sections dont work.... like Bizzards doesn't work is it due to the fact after looking into resolverurl.xxx  there no py for it... this is the site https://www.brazzers.xxx/ and the base file where it pulling the content from from the addon  base = 'http://www.ero-tik.com/index.html'

**Comment by Gujal00** [comment]
Erotik addon does not use resolveurl.xxx, so can't do anything about it. Please raise the issue with the addon developer. Closing the issue for now
