### ISSUE TITLE
Bitporno not resolve 

### ISSUE THREAD

**Issue by soter80** [jsergio123/script.module.resolveurl.xxx#9]
Bitporno not resolve
hxxps://www.bitporno.com/v/GET6OCGBJ1

**Comment by Gujal00** [comment]
Additional embed pattern added in https://github.com/jsergio123/script.module.resolveurl.xxx/commit/91d9b86286fddbacbe9be9ec86c574b497ca27fc

**Comment by soter80** [comment]
bit porno not work yet, i've tested your chenge and link not work
here is the debug log
https://pastebin.com/raw/5GHSsJry
